#!/bin/bash
#
# shared_lib - part of the MiniArch project
# Copyright (C) 2025, JustScott, development@justscott.me
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Function to show a spinner and handle exit status
task_output() {
    local pid=$1
    local stderr_path=$2
    local task_message="$3"

    local spin_chars="/-\|"

    while kill -0 "$pid" 2>/dev/null; do
        for i in $(seq 0 3); do
            printf "\r\e[36m[%s]\e[0m %s" "${spin_chars:$i:1}" "$task_message"
            sleep 0.1
        done
    done

    # Capture the exit code of the background process
    wait $pid
    local exit_code=$?

    if [ $exit_code -eq 0 ]; then
        printf "\r\e[32m[Success]\e[0m %s\n" "$task_message"
        return 0
    else
        printf "\r\e[31m[Error]\e[0m %s (Exit code: %d)\n" "$task_message" "$exit_code"
        printf "\e[31m[!] Check error log: %s\e[0m\n" "$stderr_path"
        return 1
    fi
}
